name: BTC Price Monitor

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-price:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run monitor script
        run: npm run start
        env:
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add lastData.json
          git diff --cached --quiet || git commit -m "Update lastData.json [bot]"
          git push
