name: BTC Price Monitor

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
  workflow_dispatch: # Allows manual runs

jobs:
  check-price:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run monitor script
        run: npm run start
        env:
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          API_KEY: ${{ secrets.API_KEY }}
